
/**
 * A map from Mixamo rig name to VRM Humanoid bone name
 * @see https://github.com/pixiv/three-vrm/blob/dev/packages/three-vrm/examples/humanoidAnimation/mixamoVRMRigMap.js
 */
export const mixamoGLTFRigMap:{[key:string]:string} = {
	mixamorigHips: 'mixamorigHips',
	mixamorigSpine: 'mixamorigSpine',
	mixamorigSpine1: 'mixamorigSpine1',
	mixamorigSpine2: 'mixamorigSpine2',
	mixamorigNeck: 'mixamorigNeck',
	mixamorigHead: 'mixamorigHead',
	mixamorigLeftShoulder: 'mixamorigLeftShoulder',
	mixamorigLeftArm: 'mixamorigLeftArm',
	mixamorigLeftForeArm: 'mixamorigLeftForeArm',
	mixamorigLeftHand: 'mixamorigLeftHand',
	mixamorigLeftHandThumb1: 'mixamorigLeftHandThumb1',
	mixamorigLeftHandThumb2: 'mixamorigLeftHandThumb2',
	mixamorigLeftHandThumb3: 'mixamorigLeftHandThumb3',
	mixamorigLeftHandIndex1: 'mixamorigLeftHandIndex1',
	mixamorigLeftHandIndex2: 'mixamorigLeftHandIndex2',
	mixamorigLeftHandIndex3: 'mixamorigLeftHandIndex3',
	mixamorigLeftHandMiddle1: 'mixamorigLeftHandMiddle1',
	mixamorigLeftHandMiddle2: 'mixamorigLeftHandMiddle2',
	mixamorigLeftHandMiddle3: 'mixamorigLeftHandMiddle3',
	mixamorigLeftHandRing1: 'mixamorigLeftHandRing1',
	mixamorigLeftHandRing2: 'mixamorigLeftHandRing2',
	mixamorigLeftHandRing3: 'mixamorigLeftHandRing3',
	mixamorigLeftHandPinky1: 'mixamorigLeftHandPinky1',
	mixamorigLeftHandPinky2: 'mixamorigLeftHandPinky2',
	mixamorigLeftHandPinky3: 'mixamorigLeftHandPinky3',
	mixamorigRightShoulder: 'mixamorigRightShoulder',
	mixamorigRightArm: 'mixamorigRightArm',
	mixamorigRightForeArm: 'mixamorigRightForeArm',
	mixamorigRightHand: 'mixamorigRightHand',
	mixamorigRightHandPinky1: 'mixamorigRightHandPinky1',
	mixamorigRightHandPinky2: 'mixamorigRightHandPinky2',
	mixamorigRightHandPinky3: 'mixamorigRightHandPinky3',
	mixamorigRightHandRing1: 'mixamorigRightHandRing1',
	mixamorigRightHandRing2: 'mixamorigRightHandRing2',
	mixamorigRightHandRing3: 'mixamorigRightHandRing3',
	mixamorigRightHandMiddle1: 'mixamorigRightHandMiddle1',
	mixamorigRightHandMiddle2: 'mixamorigRightHandMiddle2',
	mixamorigRightHandMiddle3: 'mixamorigRightHandMiddle3',
	mixamorigRightHandIndex1: 'mixamorigRightHandIndex1',
	mixamorigRightHandIndex2: 'mixamorigRightHandIndex2',
	mixamorigRightHandIndex3: 'mixamorigRightHandIndex3',
	mixamorigRightHandThumb1: 'mixamorigRightHandThumb1',
	mixamorigRightHandThumb2: 'mixamorigRightHandThumb2',
	mixamorigRightHandThumb3: 'mixamorigRightHandThumb3',
	mixamorigLeftUpLeg: 'mixamorigLeftUpLeg',
	mixamorigLeftLeg: 'mixamorigLeftLeg',
	mixamorigLeftFoot: 'mixamorigLeftFoot',
	mixamorigLeftToeBase: 'mixamorigLeftToeBase',
	mixamorigRightUpLeg: 'mixamorigRightUpLeg',
	mixamorigRightLeg: 'mixamorigRightLeg',
	mixamorigRightFoot: 'mixamorigRightFoot',
	mixamorigRightToeBase: 'mixamorigRightToeBase',
};
